### ISSUE TITLE
SyncManager cancels SyncAdapters that are still making progress

### ISSUE THREAD

**Issue by rburgst** [aosp-mirror/platform_frameworks_base#103]
With the following commit, my sync adapter is getting cancelled even though its still progressing

https://github.com/android/platform_frameworks_base/commit/1967c8ddd5bb46958b732002d391e4276c0710c4 by @mjwilliams43

The problem is that I download all files upfront and then process these in a batch. Depending on the size of the update files, processing can take quite a while.

The mentioned patch enforces "bad behaviour" where syncadpaters would only download the pieces needed and then process them directly. In order to keep battery and network utilisation low IMHO its smarter to perform all downloads in one batch.
### Recommendation:

The SyncAdapter API has APIs where a sync adapter can advertise whether it made progress or not (SyncStatus.numDeletes, ...). I would suggest that before cancelling a sync the SyncManager should also consider these values before making a decision.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
