### ISSUE TITLE
How to use this app ?

### ISSUE THREAD

**Issue by gurappa** [aosp-mirror/platform_frameworks_base#104]
Hi,

I am not getting on how to use this and how do I get statistics to analyse ?
Help me with info.

Thanks,
Guru

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
