### ISSUE TITLE
android_audioRecorder_realize(0xab70c5c0) error creating AudioRecord object, crash at AudioRecord::stop()

### ISSUE THREAD

**Issue by brucejee** [aosp-mirror/platform_frameworks_base#107]
04-19 16:59:35.568 I/VOIPENGINE( 1469): 16:59:35.568   opensl_dev.c  ....config rtc agc success
04-19 16:59:35.569 D/AudioTrack( 1469): audiotrack 0xab70aee0 set Type 3, rate 16000, fmt 1, chn 1, fcnt 0, flags 0004
04-19 16:59:35.569 D/AudioTrack( 1469): mChannelMask 0x1
04-19 16:59:35.570 W/AudioTrack( 1469): AUDIO_OUTPUT_FLAG_FAST denied by client
04-19 16:59:35.571 D/ChatStatusTextView( 1469): updateTextContentStatus: status = SHOW_NAME, textContent = 测试
04-19 16:59:35.572 D/AudioTrackCenter( 1469): addTrack, trackId:0xe1dce000, frameCount:1486, sampleRate:16000, trackPtr:0xab70aee0
04-19 16:59:35.572 D/AudioTrackCenter( 1469): mAfSampleRate 44100, sampleRate 16000, AfFrameCount 1024 , mAfSampleRate 44100, frameCount 1486
04-19 16:59:35.572 D/AudioRecord( 1469): openRecord_l
04-19 16:59:35.573 W/AudioRecord( 1469): AUDIO_INPUT_FLAG_FAST denied by client
04-19 16:59:35.573 I/FlowWindowModelManager( 1469): onTalkStateChange: preTalkState = MICROCALL_TALK_STATE_IDLE, currentTalkState = MICROCALL_TALK_STATE_APPLYTALK, isCaller = true
04-19 16:59:35.573 I/MicroCallUIResponder( 1469): onTalkStateChange microCallInterface = com.cootek.andes.voip.engine.MicroCallProxy@1f617a85, prevTalkState = MICROCALL_TALK_STATE_IDLE, currentTalkState = MICROCALL_TALK_STATE_APPLYTALK, talkResponseState = null
04-19 16:59:35.582 E/AudioRecord( 1469): AudioFlinger could not create record track, status: -1
04-19 16:59:35.587 E/libOpenSLES( 1469): android_audioRecorder_realize(0xab70c5c0) error creating AudioRecord object
04-19 16:59:35.587 W/libOpenSLES( 1469): Leaving Object::Realize (SL_RESULT_CONTENT_UNSUPPORTED)
04-19 16:59:35.587 I/VOIPENGINE( 1469): 16:59:35.587   opensl_dev.c  ....Cannot realize recorder : 9
04-19 16:59:35.588 I/VOIPENGINE( 1469): 16:59:35.588   opensl_dev.c  ....Stopping stream
04-19 16:59:35.590 I/VOIPENGINE( 1469): 16:59:35.590   opensl_dev.c  ....OpenSL stream stopped
04-19 16:59:35.591 D/AudioTrack( 1469): ~audioTrack 0xab70aee0
04-19 16:59:35.591 D/AudioTrackCenter( 1469): removeTrack, trackPtr:0xab70aee0
04-19 16:59:35.592 D/AudioRecord( 1469): stop

SL_RESULT_CONTENT_UNSUPPORTED this code is return when i set this app have no audio record permission. Can return SL_RESULT_PERMISSION_DENIED when have no record permission?

I found someone report the bug at https://code.google.com/p/android/issues/detail?id=37905.
Some member in AudioRecord class is not initialized in constructor, but stop() function will have random values when AudioRecord object construct failed.
Please fix this bug.

**Comment by brucejee** [comment]
I also report this bug here https://code.google.com/p/android/issues/detail?id=207508

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
