### ISSUE TITLE
Where can I get the document ?

### ISSUE THREAD

**Issue by ComputerScientistLee** [aosp-mirror/platform_frameworks_base#108]
I would like to get the document that explains internal android framework. I don't mean the document for application level which is in http://developer.android.com/ 
I searched google for several days but I could not find it. I guess this exists here but I can't find it.

where can I get the document?

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
