### ISSUE TITLE
What is the password?

### ISSUE THREAD

**Issue by AlanCheen** [aosp-mirror/platform_frameworks_base#109]
I download the zip,but it needs a pwd.

**Comment by marcusbecker** [comment]
There is no password.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
