### ISSUE TITLE
Compiling "content" adb command for pre-ICS

### ISSUE THREAD

**Issue by maaaaz** [aosp-mirror/platform_frameworks_base#113]
Hello there,
I just realized that the [`content` command](https://github.com/android/platform_frameworks_base/tree/master/cmds/content), used to interact with content providers, wasn't available for pre-ICS versions.

So I do have 2 questions :
- Do you think the current version could be backported "as-is" ?
- If not, I'd like to create a simili-backport by implementing a small client in Java: could you at least tell me how could I compile a **standard Java application into an Android executable** (that could be called from adb).

I know that this request might sound weird but I need it (and I need to practice with NDK :)).

Cheers!

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
