### ISSUE TITLE
Invalid Slide Direction Exception API 21

### ISSUE THREAD

**Issue by StuStirling** [aosp-mirror/platform_frameworks_base#116]
Running into an issue with the following. Getting a crash when trying to create a new `Slide` object with the `slideEdge` set to `Gravity.END`. 

Works fine on API 22. Here is my code.

``` java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP ) {
    helpFrag.setEnterTransition( new Slide(Gravity.END) );
    helpFrag.setSharedElementEnterTransition( new ButtonTransition() );
    helpFrag.setSharedElementReturnTransition(new ButtonTransition());
    loginFragment.setExitTransition( new Slide(Gravity.START));
}
```

Had a look at the source code at the exception and can see the method of the `Slide` class where it's crashing. Here is what it looks like.

``` java
public void setSlideEdge(int slideEdge) {
        switch (slideEdge) {
            case Gravity.LEFT:
                mSlideCalculator = sCalculateLeft;
                break;
            case Gravity.TOP:
                mSlideCalculator = sCalculateTop;
                break;
            case Gravity.RIGHT:
                mSlideCalculator = sCalculateRight;
                break;
            case Gravity.BOTTOM:
                mSlideCalculator = sCalculateBottom;
                break;
            case Gravity.START:
                mSlideCalculator = sCalculateStart;
                break;
            case Gravity.END:
                mSlideCalculator = sCalculateEnd;
                break;
            default:
                throw new IllegalArgumentException("Invalid slide direction");
        }
        mSlideEdge = slideEdge;
        SidePropagation propagation = new SidePropagation();
        propagation.setSide(slideEdge);
        setPropagation(propagation);
    }
```

As you can see `Gravity.END` is checked for.

**Comment by kimbaudi** [comment]
I also encountered this error on a Samsung Galaxy Tab S 10.5-Inch (Android 5.0.2, API 21). `Gravity.START` throws `IllegalArgumentException: Invalid slide direction`

![a](https://cloud.githubusercontent.com/assets/1864092/17452987/1c5baeb2-5b2a-11e6-8d30-2f7f2758714b.png)

![b](https://cloud.githubusercontent.com/assets/1864092/17452990/2737195c-5b2a-11e6-8bd3-29fb74375ea5.png)

**Comment by jotaemepereira** [comment]
Any update on this? I got the same problem on a Sony E2306 with Android 5.0

**Comment by lewismcgeary** [comment]
See this StackOverflow answer: http://stackoverflow.com/a/39512723/5251523

The Api 21 version of `Slide` doesn't support `START` & `END` but you can use `GravityCompat` which will convert START/END to LEFT/RIGHT as appropriate.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
