### ISSUE TITLE
Adding user acceleration and gravitational component incorrectly

### ISSUE THREAD

**Issue by inigo333** [aosp-mirror/platform_frameworks_base#117]
Correct me if I'm wrong, but I feel like there is something wrong while reading the _SensorEvent.java_ file. I'm assuming it is trying to show the total acceleration of the device (user acceleration+gravity), which I think it is, as it is showing "9.8" values when the device is static.

As per this document mentioned above, it is said in the examples that:

> Examples
> 1. When the device lies flat on a table and is pushed on its left side toward the right, the x acceleration value is positive.
> 2. When the device lies flat on a table, the acceleration value is +9.81, which correspond to the acceleration of the device (0 m/s^2) minus the force of gravity (-9.81 m/s^2).
> 3. When the device lies flat on a table and is pushed toward the sky with an acceleration of A m/s^2, the acceleration value is equal to A+9.81 which correspond to the acceleration of the device (+A m/s^2) minus the force of gravity (-9.81 m/s^2).

I totally agree with 1. But not with 2 nor 3.

In number 2 shouldn't the **total acceleration be the SUM of all accelerations**?
`TotalAccel = UserAccel + Gravity`
`(x,y,z) = (0,0,0)+(0,0,-9.8)`
`(x,y,z) = (0,0,-9.8)`
However, the document states that it should be:
`TotalAccel = UserAccel - Gravity`
`(x,y,z) = (0,0,0)-(0,0,-9.8)`
`(x,y,z) = (0,0,+9.8)`
Which I believe is wrong

This reasoning applies for number 3 as well. I think it should be:
`TotalAccel = UserAccel + Gravity`
`(x,y,z) = (0,0,A)+(0,0,-9.8)`
`(x,y,z) = (0,0,A-9.8)`
However, the document states that it should be:
`TotalAccel = UserAccel - Gravity`
`(x,y,z) = (0,0,A)-(0,0,-9.8)`
`(x,y,z) = (0,0,A+9.8)`
Which again, I believe is wrong.

Could someone clarify or look into this, please?
Thanks in advance,
Inigo M

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
