### ISSUE TITLE
Enhancement - provide API to force recheck captive portal

### ISSUE THREAD

**Issue by hexadec** [aosp-mirror/platform_frameworks_base#119]
Now it is impossible for apps that log in to captive portals to nofity the system that the network is validated and remove the notification and the exclamation mark.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
