### ISSUE TITLE
NPE when calling the getNetworkInfoForNetwork(Network network) on ConnectivityManager

### ISSUE THREAD

**Issue by mariusc83** [aosp-mirror/platform_frameworks_base#123]
It seems that for a specific Network (netId=100) whenever I call the getNetworkForNetwork on the ConnectivityManager a NullPointerException is thrown: 
`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.NetworkInfo$State.name()' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1605)
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.net.IConnectivityManager$Stub$Proxy.getNetworkInfoForNetwork(IConnectivityManager.java:1175)
       at android.net.ConnectivityManager.getNetworkInfo(ConnectivityManager.java:793)`

This only happens on that specific Network, happens randomly on different devices and SDK versions and based on my tests is thrown by the Native Process inside the `IConnectivityManager` class.

**Comment by test01wrk** [comment]
Same problem here. It happens randomly on different devices when I call:
`connectivityManager.getNetworkInfoForNetwork(wifiManager.getCurrentNetwork())`

**Comment by mvysny** [comment]
This happens on Android 6.0.1 and 6.0, Sony and Samsung phones. My code looks like follows:
```
final Network[] networks = connectivityManager.getAllNetworks();
if (networks != null) {
  for (Network network : networks) {
  if (network != null) {
     // here it throws NPE
     connectivityManager.getNetworkInfo(network);
  }
}
```

**Comment by sisel** [comment]
same bug reported by 

Android 6.0.1,level 23
ROM:XiaoMi/MIUI
device:Mi5
```
Caused by:
java.lang.NullPointerException:Attempt to invoke virtual method 'java.lang.String android.net.NetworkInfo$State.name()' on a null object reference
android.os.Parcel.readException(Parcel.java:1626)
android.os.Parcel.readException(Parcel.java:1573)
android.net.IConnectivityManager$Stub$Proxy.getNetworkInfoForNetwork(IConnectivityManager.java:1104)
android.net.ConnectivityManager.getNetworkInfo(ConnectivityManager.java:752)
```

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
