### ISSUE TITLE
listview items sometimes not clickable on Android 7.X

### ISSUE THREAD

**Issue by holoduke** [aosp-mirror/platform_frameworks_base#128]
The method 
handleBoundsChange in 
https://github.com/android/platform_frameworks_base/blob/master/core/java/android/widget/AbsListView.java is setting mDataChanged to true. My question is why? It is called from internalSetPadding.
On Android 7.x this results in scenarios that list items become not clickable
(on line 4016 of AbsListView.java there is a check which requires mDataChanged to be false in order to allow the touch up event to be fired.
This scenario only happens when the list is rendered for the first time. As soon as the user scrolls the mDataChanged property is set to false and everything works again. I also noted that the list should have more items than the list can show to expose the issue.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
