### ISSUE TITLE
Proposal: UIToast spec to prevent permission issues when using Toast

### ISSUE THREAD

**Issue by ChrisCates** [aosp-mirror/platform_frameworks_base#129]
A common recurring problem while utilizing the ever so useful `Toast` tool is that users get a permission issue for the `Screen Overlay Detected` to enable drawing on the screen. And yes, my users are downloading off the Google Play Store and getting this issue on fresh install or uninstall and reinstall.

While commonly, the `Toast` tool is extremely handy to run as an overlay for certain use cases outside of the app. I'd still LOVE to see Toast stay the same.

However, I propose that we have `UIToast` that runs on the UI Thread only... And must be declared in that scope specifically.

I am more then happy to write the associated code in order to implement this, granted you approve me writing such a pull request.

Also explicitly updating the Android Developer documentation explaining the context of both UIToast and Toast would be great. Once again, more then happy to do a write up.

Thank you,
Chris Cates

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
