### ISSUE TITLE
custom view onMeasure exception occured as a child of RelativeLayout

### ISSUE THREAD

**Issue by brekov** [aosp-mirror/platform_frameworks_base#132]
in my custom view:
```    
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        int widthMode = MeasureSpec.getMode(widthMeasureSpec);
        int heightMode = MeasureSpec.getMode(heightMeasureSpec);
        int widthSize = MeasureSpec.getSize(widthMeasureSpec);
        int heightSize = MeasureSpec.getSize(heightMeasureSpec);
        int size = Math.min(widthMeasureSpec, heightMeasureSpec);
        setMeasuredDimension(size, size + radius * 2);
    }
```   
then i set the custom view as a child of RelativeLayout with attributes `android:layout_width="200dp"  android:layout_height="100dp"`  in layout.xml

expected： custom view  width=100dp  height=100dp
result:  custom view  width=200dp  height=100dp

why?

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
