### ISSUE TITLE
MediaProjection  createVirtualDisplay  throw   Invalid media projection  , who knows the reason. 

### ISSUE THREAD

**Issue by zhang-yuehuan** [aosp-mirror/platform_frameworks_base#133]
MediaProjection  createVirtualDisplay  throw   Invalid media projection  , who can tell why ? 

DisplayManagerService.java   createVirtualDisplay  
 if (!getProjectionService().isValidMediaProjection(projection)) {
      throw new SecurityException("Invalid media projection");
} 

then 
MediaProjectionManagerService.java   isValidMediaProjection(IBinder token)   return false. 
   private boolean isValidMediaProjection(IBinder token) {
        synchronized (mLock) {
            if (mProjectionToken != null) {
                return mProjectionToken.equals(token);
            }
            return false;
        }
    }

who can help me , Thanks a lot .

**Comment by viswesvar** [comment]
i am not sure but i think it is trows null instantly 
if ( mProjectToken == null ) {
      return ;   //update here return accordingly 
    }

**Comment by zhang-yuehuan** [comment]
yes, I also think so. but  i  don't know why mProjectToken == null .  
 in function startProjectionLocked,  create instance. 
 private void startProjectionLocked(final MediaProjection projection) {
        if (mProjectionGrant != null) {
            mProjectionGrant.stop();
        }
        if (mMediaRouteInfo != null) {
            mMediaRouter.getDefaultRoute().select();
        }
        mProjectionToken = projection.asBinder();
        mProjectionGrant = projection;
        dispatchStart(projection);
    }
in function stopProjectionLocked , mProjectToken == null 
private void stopProjectionLocked(final MediaProjection projection) {
        mProjectionToken = null;
        mProjectionGrant = null;
        dispatchStop(projection);
    }

i don't use other functions  .  I just use like this 
ImageReader imageReader = ImageReader.newInstance(width, height, PixelFormat.RGBA_8888, 2);
VirtualDisplay virtualDisplay = mMediaProjection.createVirtualDisplay(
                "screen-mirror",
                width,
                height,
                mScreenDensity,
                DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,
                imageReader.getSurface(),
                null,
                null);

**Comment by 294485329peng** [comment]
Is this the problem solved?

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
