### ISSUE TITLE
LED notification service stopped/ timeout

### ISSUE THREAD

**Issue by 1Jesper1** [aosp-mirror/platform_frameworks_base#136]
The LED light sometimes suddenly stops working when I'm posting multiple notifications which uses setLight. Is there a particular event happening and maybe visible in the logs? I can't find an error happening. Also the lightsservice is still setting the LED light. After I restart my Samsung S6, the LED light is working again.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
