### ISSUE TITLE
Bug in TimePicker widget

### ISSUE THREAD

**Issue by yankovskiy** [aosp-mirror/platform_frameworks_base#139]
I have found some problem for TimePicker widget. After user change time in widget setHour and setMinute methods not works.

```
public class MainActivity extends AppCompatActivity {

    private Button mButton;
    private TimePicker mTimePicker;

    private static final String TAG = "MainActivity";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mButton = (Button) findViewById(R.id.reset);
        mTimePicker = (TimePicker) findViewById(R.id.timePicker);

        mButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Calendar cal = Calendar.getInstance();
                int hour = cal.get(Calendar.HOUR_OF_DAY);
                int minute = cal.get(Calendar.MINUTE);

                mTimePicker.setHour(hour);
                mTimePicker.setMinute(minute);

                Log.v(TAG, "onClick: " + hour + "=>" + mTimePicker.getHour());
                Log.v(TAG, "onClick: " + minute + "=>" + mTimePicker.getMinute());
            }
        });
    }
}
```
Step for reproduce:

1.Run app (my time: 13:21)
2.Change time on the Widget (21:21)
3.Tap on the Reset button

Result: time not reset to 13:21

Log:

> 03-30 13:18:05.765 30923-30923/ru.neverdark.timepickerproblem V/MainActivity: onClick: 13=>21 03-30 13:18:05.765 30923-30923/ru.neverdark.timepickerproblem V/MainActivity: onClick: 18=>18

Any fix or workaround for this?

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
