### ISSUE TITLE
getService null exception on the intent

### ISSUE THREAD

**Issue by tergabri** [aosp-mirror/platform_frameworks_base#144]
I found a strange behaviour in getService, in PendingIntent.java

```
    public static PendingIntent getService(Context context, int requestCode,
            @NonNull Intent intent, @Flags int flags) {
        String packageName = context.getPackageName();
        String resolvedType = intent != null ? intent.resolveTypeIfNeeded(
                context.getContentResolver()) : null;
        try {
            intent.prepareToLeaveProcess(context);
            IIntentSender target =
                ActivityManagerNative.getDefault().getIntentSender(
                    ActivityManager.INTENT_SENDER_SERVICE, packageName,
                    null, null, requestCode, new Intent[] { intent },
                    resolvedType != null ? new String[] { resolvedType } : null,
                    flags, null, UserHandle.myUserId());
            return target != null ? new PendingIntent(target) : null;
        } catch (RemoteException e) {
        }
        return null;
    }
```

intent is marked as not null (@NonNull Intent intent)
but we still have this
`        String resolvedType = intent != null ? intent.resolveTypeIfNeeded(
                context.getContentResolver()) : null;`

I think it can be removed. 
I can patch the code if you are happy with that.

Later we have this:
`            intent.prepareToLeaveProcess(context);`

So clearly it cannot be null

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
