### ISSUE TITLE
About Location Class in package of android.location

### ISSUE THREAD

**Issue by Reed-Xiong** [aosp-mirror/platform_frameworks_base#149]
I'm a map developer in android platform,but I met a annoying question in usual that I need handle a serious location data. For example,I need define a location class for Bing map, and then define a location class for open street map, and so on. I cannot override my code by Polymorphic  property,because location class in android framework cannot implement interface for third party to implementation.

why not change location class and add interface to implement?

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
