### ISSUE TITLE
DatePicker locale inconsistencies

### ISSUE THREAD

**Issue by bradvolen** [aosp-mirror/platform_frameworks_base#150]
I made a test application that has a DatePicker initialized as such

    <DatePicker
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:calendarViewShown="false"
        android:datePickerMode="spinner"
        android:minDate="01/01/1900"
        android:maxDate="12/31/2100" />

The behavior of this date picker is different on my OnePlus 3 and my Pixel.

When I set the language to Arabic Saudi Arabia the OnePlus3 starts to use the Hijri calendar and the Pixel stays with the Gregorian calendar.

To really show the difference, if I remove the minDate and maxDate params, the Pixel initializes to the current date. But the OnePlus3 initializes to the default minimum date of "01/01/1900" in the Hijri system as the current date is much earlier than this.

I believe this inconsistency also exists between the Nexus 6P and the Pixel; though I don't have the 6P handy to confirm on my test app.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
