### ISSUE TITLE
i want to add somali language 

### ISSUE THREAD

**Issue by baaslaawe** [aosp-mirror/platform_frameworks_base#154]
hello 
i am awale , i am interest to contribute to somali language ,

so how can i start , how can i translate and how can i add

thank you

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
