### ISSUE TITLE
Is there any new interface to dismiss keyguard when unlocking device with Fingerprint from a Locker App?

### ISSUE THREAD

**Issue by dcf82** [aosp-mirror/platform_frameworks_base#157]
Hi,

I'm seeing that in Android O, the following method was deleted in the class:

 platform_frameworks_base/services/core/java/com/android/server/policy/keyguard/KeyguardServiceDelegate.java

the method is called keyguardDone(bool, bool), I used it to dismiss the SystemUI/Keyguard on a Locker App when a user authenticates successfully with the Fingerprint sensor.

On Android Oreo this method was deleted, so is there a new method/interface/service to use to get the same functionality?

Thanks a lot for your feedback
David

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
