### ISSUE TITLE
Typo in String in Activity.java

### ISSUE THREAD

**Issue by stefmorren** [aosp-mirror/platform_frameworks_base#158]
I want to report a typo mistake in the Activity.java class. If you go to the method requestPermissions, there is a log string with as text "Can req**eu**st only one set of permissions at a time").

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
