### ISSUE TITLE
PatternsTest#testAutoLinkWebUrl_doesNotMatchUnicodeSpaces fails

### ISSUE THREAD

**Issue by argorf** [aosp-mirror/platform_frameworks_base#163]
PatternsTest#testAutoLinkWebUrl_doesNotMatchUnicodeSpaces failure. Anyone else getting the same?

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
