### ISSUE TITLE
Typo in Handler Class

### ISSUE THREAD

**Issue by martinomburajr** [aosp-mirror/platform_frameworks_base#168]
The Handler class within the core/java/android/os/Handler.java directory has a typo in one of the docs on line 36. 

It currently reads:
"... runnables to be executed **as** some point in the future"
It shall be changed to:
"... runnables to be executed **at** some point in the future"

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
