### ISSUE TITLE
Just a question not a issue, set object to null

### ISSUE THREAD

**Issue by hxlich** [aosp-mirror/platform_frameworks_base#169]
Is is set null a good practice for Android? Understand Android VM is not same as JVM, but have not find a solid source to clarify.

https://github.com/aosp-mirror/platform_frameworks_base/blob/fe79660d1efde025a3a28d2b185a443d0c8b1b49/core/java/android/webkit/WebViewFragment.java#L87

ref:https://stackoverflow.com/questions/14058834/is-it-a-good-practice-to-set-an-object-to-null-after-processing

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
