### ISSUE TITLE
Sharing internet from Bluetooth via Wi-Fi hotspot

### ISSUE THREAD

**Issue by 7storm7** [aosp-mirror/platform_frameworks_base#171]
With the platform version 8.1.0, the Bluetooth tethered internet could not be shared via Wi-Fi AP. The problem is that, in TetheringConfiguration.java, the preferredUpstreamIfaceTypes array does not contain TYPE_BLUETOOTH as a preferred upstream network interface for tethering. 

Solution:
I added a line into the getUpstreamIfaceTypes function which contains fixes for adding some additional upstream types into the array.
I added following line before the return statement:
upstreamIfaceTypes.add(TYPE_BLUETOOTH);

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
