### ISSUE TITLE
OnTextChanged and InputFilter filter methods get drastically different values on different keyboards

### ISSUE THREAD

**Issue by nzackoya** [aosp-mirror/platform_frameworks_base#172]
How that can happen that  OnTextChanged and InputFilter filter methods get drastically different values on different keyboards? Tested Android AOSP, Gboard and Swiftkey. They really work different. Andriod team seems hasn't any restrictions on creating keyboards.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
