### ISSUE TITLE
大家看源码一般用什么工具看啊

### ISSUE THREAD

**Issue by GHYOWEE** [aosp-mirror/platform_frameworks_base#173]
Top Top

**Comment by YunanChen** [comment]
You can use the Android Studio. At first you should compile the aosp, then follow the steps at this blog https://blog.csdn.net/songjinshi/article/details/53020549 （Thanks the author）. 
Enjoy reading the fxxxing source code.

**Comment by DawnYu9** [comment]
@YunanChen It doesn't support Windows.

**Comment by ldrong** [comment]
sourceInsight

**Comment by daking1991** [comment]
Understand

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://android.github.io/.
