### ISSUE TITLE
Why didn't see SurfaceFlinger.cpp file?

### ISSUE THREAD

**Issue by pop1030123** [aosp-mirror/platform_frameworks_base#174]
Why didn't see SurfaceFlinger.cpp file?

**Comment by YunanChen** [comment]
@pop1030123 SurfaceFlinger.cpp is at framework/native rather than framework/base.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://android.github.io/.
