### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by cRAN-cg** [aosp-mirror/platform_frameworks_base#179]
https://github.com/aosp-mirror/platform_frameworks_base/blob/940a9e95dff8b67f3a690602c186ba86d8460410/opengl/java/android/opengl/GLSurfaceView.java#L459

Was going through the docs and the `&` was wrongly typed as `@`. Would love to make a PR but I have a strong feeling that it wouldn't get merged. So could you help us updating the docs. :))

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://android.github.io/.
