### ISSUE TITLE
Support AAPT for ARM HardFloat ABI

### ISSUE THREAD

**Issue by MisterGitHubber** [aosp-mirror/platform_frameworks_base#180]
Hello everyone!!! I need to run aapt command on Android (ARM Hard Float ABI). Tell me please whether there is a reason to wait for this. I am developing android studio on android and I can not use aapt. Help me please!! or is it possible to port it?

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://android.github.io/.
