### ISSUE TITLE
Launching activities in free form multi window mode is disabled in android-9.0.0_r3 release

### ISSUE THREAD

**Issue by somsubhojit1988** [aosp-mirror/platform_frameworks_base#181]
Hi
I have been working on a launcher application which launches multiple activities from same(or different applications in free form mode), I have been testing my application on emulator built from AOSP branch **android-8.1.0_r43**, and it worked fine although I did have to enable the `enable_freeform_support ` flag from the shell.
However after the release of android-9.0.0_r3 branch, when I run the same application on the emulator built from the source tree, the activities are no longer launched in free form windows but all in full screen mode. 
Is there something I am missing which I need to do, before I can get the free form mode to work on this branch.
Thanks in advance.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://android.github.io/.
