### ISSUE TITLE
Status bar clock has moved to badly placed location.

### ISSUE THREAD

**Issue by pronto** [aosp-mirror/platform_frameworks_base#182]
Android 9 is forcing the status bar clock to the left side of the screen.
This should be a toggleable option, or one that is set automatically depending if the device has a notch.

It's poor UI/UX decision to suddenly force something like this.  Around 15 years of muscle memory checking the time has been thrown out of the window.

commit: https://github.com/aosp-mirror/platform_frameworks_base/commit/2cf5682a60e3241515efe27059da9251edc31969

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://android.github.io/.
