### ISSUE TITLE
java.lang.NoSuchMethodError: android.os.FileUtils.getFatVolumeId 

### ISSUE THREAD

**Issue by onewilk** [aosp-mirror/platform_frameworks_base#28]
My Nexus5 was updated android 4.4.2 by OTA,then my application exception now ,the Log is 

CrashHandler(6192): java.lang.NoSuchMethodError:android.os.FileUtils.getFatVolumeId

so where is the method of "getFatVolumeId()"???

**Comment by krystian71115** [comment]
FileUtils is hidden api. Don't use hidden apis because it can be removed in the future.
For example. ConnectivityManager.setMobileDataEnabled not exists now.

**Comment by Austin503** [comment]
Master

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
