### ISSUE TITLE
Can you add a mirror for platform/libcore ?

### ISSUE THREAD

**Issue by yogurtearl** [aosp-mirror/platform_frameworks_base#30]
Can you add a mirror for platform/libcore ?

https://android.googlesource.com/platform/libcore/

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
