### ISSUE TITLE
Running service under Android multi-user profile

### ISSUE THREAD

**Issue by nikhilbchilwant** [aosp-mirror/platform_frameworks_base#37]
I'm building a service. Now, I want to make two users for app: admin and other. Admin will start the service. Now, I want this service to run even after admin logs out. Is it possible? If possible, I want to add: this service will create some notification periodically. I want to show those notifications to all users but only other user should be able to stop the service. There is a feature for multi-user in Android 4.4 but they haven't mentioned specifically whether this can be done or not. There are apps like switch me but again, they do not mention explicitly for this.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
