### ISSUE TITLE
Android Lock Screen Security Vulnerability

### ISSUE THREAD

**Issue by wingoku** [aosp-mirror/platform_frameworks_base#41]
I had developed a Ubuntu style launcher which can be accessed by swiping from the left edge of the screen & recently unearthed a vulnerability hidden in Android OS with the help of it.

The vulnerability I found on lock screen is hidden in the emergency dialer. I think the emergency dialer's parent view (the one encapsulating the buttons & other UI elements of the emergency dialer) is not a Frame Layout. This allows my launcher to open all the apps (only those apps can be accessed that are selected by the user to quickly access through out the OS). 
# Android OS Version:

Jelly Bean 4.1 -> Android L Developer Preview
# Scenario for the vulnerability:

However, this vulnerability only effects the root users who have installed the Xposed Framework, which allows users to open multi-windows on the screen.
# Propose Solution:

This vulnerability can be fixed by changing the parent view of the emergency dialer to be a Frame Layout. 
# More Details:

http://www.wingoku.com

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
