### ISSUE TITLE
Add OTF fonts

### ISSUE THREAD

**Issue by PanderMusubi** [aosp-mirror/platform_frameworks_base#49]
Could you please add also OTF fonts to https://github.com/android/platform_frameworks_base/tree/master/data/fonts

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
