### ISSUE TITLE
screencap

### ISSUE THREAD

**Issue by ebortolini** [aosp-mirror/platform_frameworks_base#56]
Hi,
it's possible to make an executable from screencap and call it from java code to take screen shots. Is there an example showing basic steps to do it (what I need to download to compile executable ... device need to be rooted ....)?

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
