### ISSUE TITLE
Something wrong with Droid Sans Fallback

### ISSUE THREAD

**Issue by ytx21cn** [aosp-mirror/platform_frameworks_base#59]
The font Droid Sans Fallback fetched from this repository has many glyphs missing. 
For instance, in the Basic Latin block, most characters are displayed in rectangles. (You can figure this out by using BabelMap. Download BabelMap from http://www.babelstone.co.uk/Software/BabelMap.html)
Similar problems also occur in other unicode blocks. 
I tried to extract the Droid Sans Fallback font from my HUAWEI phone and there were no such problems occur.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
