### ISSUE TITLE
Targets of a Transition is not removed while using removeTarget (int targetId)

### ISSUE THREAD

**Issue by Avinash-Bhat** [aosp-mirror/platform_frameworks_base#62]
Consider the following code:

```
 Transition transition = ...;

 transition.addTarget(R.id.my_view);

 ...

 transition.removeTarget(R.id.my_view);
```

It is apparent from the [documentation](https://developer.android.com/reference/android/transition/Transition.html#removeTarget%28int%29) that the call to `Transition.removeTarget(int)` should remove the view with id `R.id.my_view` being included in further transitions. But instead the following error will be shown:

```
 Caused by: java.lang.IndexOutOfBoundsException: Invalid index <some-random-int>, size is 1
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.remove(ArrayList.java:403)
```

this is because the implementation is calling ArrayList.remove(int) instead of ArrayList.remove(Object).

_PS: this is same as http://b.android.com/167061_

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
