### ISSUE TITLE
Disable GitHub issues, pull requests, and wiki

### ISSUE THREAD

**Issue by krschultz** [aosp-mirror/platform_frameworks_base#76]
Since these GitHub repos are [only mirrors of the official repos](http://android.github.io/), there doesn't seem to be a need to have issues, pull requests, or wikis enabled. I believe people are now [spamming](https://github.com/android/platform_frameworks_base/issues/75) the repos' issues section to send emails to everyone that is watching. GitHub has an option to turn off all of three of those through the settings screen or the [API](https://developer.github.com/v3/repos/#edit).

**Comment by wsdjeg** [comment]
due to the GFW,I can not view the origin web,so please do not close the issues,thank you

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
