### ISSUE TITLE
DCIM/.thumbnails grows to fill multiple GB

### ISSUE THREAD

**Issue by DrAzraelTod** [aosp-mirror/platform_frameworks_base#79]
there are multiple tickets in different projects, all describing the same problem. Android Imagepreview saves thumbnails of all images encountered to internal storage. On my Device (Sony Z3C, Android 5.1.1) this amounts now to 4GB, to accomodate a large collection of photos on SD-Card. Photo-Storage is already set to be external, but regardless of that setting, 4GB of Cache is just hilarious.

https://jira.cyanogenmod.org/browse/CYAN-1173
https://code.google.com/p/android/issues/detail?id=39546
https://code.google.com/p/android/issues/detail?id=88651

These tickets often get closed because they were created for a previous version, but it wasn't ever fixed anywhere.

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
