### ISSUE TITLE
WindowManager can crashed the Android System with error param

### ISSUE THREAD

**Issue by ZhaoKaiQiang** [aosp-mirror/platform_frameworks_base#85]
I found a more serious Android system bug today, only the following three lines of code, you can make Android system no response:

今天在做测试的时候，发现了Android系统的一个比较严重的BUG，只需要下面三行代码，就可以把整个Android系统搞崩：

```

     WindowManager.LayoutParams layoutParams = new WindowManager.LayoutParams();
        layoutParams.x = Integer.MAX_VALUE;
        ((WindowManager) getSystemService(WINDOW_SERVICE)).addView(new View(this), layoutParams);

```

Guess the reason : x attribute overflow caused WindowManagerService collapse, and the SystemServer collapse also.
猜测原因是：x属性溢出造成WindowManagerService崩溃，顺便把SystemServer搞崩了...😄

you can contact me with my email:419927089@qq.com

你可以通过我的email联系到我，很乐意能帮助Android解决这个BUG

Demo: [https://github.com/ZhaoKaiQiang/CrashDemo](https://github.com/ZhaoKaiQiang/CrashDemo)

**Comment by banxi1988** [comment]
Hi,Thanks for you feedback. While The Repo is just a Mirror.
Report bug please go https://code.google.com/p/android/issues/list

Hi，只是这个仓库只是一个方便查看的镜像而已，并不接收 PR 和 issue ，发 issue 的话
 建议到 Android 项目专门的地方去。 https://code.google.com/p/android/issues/list

**Comment by ZhaoKaiQiang** [comment]
Got it ! Thanks ！

**Comment by wtjandjay** [comment]
微博观光团前来看大神怎么解决这个问题

**Comment by NiaNingXue** [comment]
中英双语真是吊

**Comment by elsdnwn** [comment]
凯子哥，解决了么？

**Comment by ZhaoKaiQiang** [comment]
上报给Android issues list 了 @elsdnwn

**Comment by erhu** [comment]
not work in 5.1.1;

**Comment by yuanhuihui** [comment]
折腾半天，发现使用vpn，也无法 repo sync google官网的android code，由于同步过程，会出现中断，一旦中断，下次有需要重头sync，尝试了很多次都无法成功。后来才想到来github的 android的主页来提交PR。刚刚看到该issues的 @banxi1988 回答，才知道 这个仓库只是一个方便查看的镜像而已，并不接收 PR ，有点失望啊。 有没有谁知道有啥途径能给android提交代码。

**Comment by zwlin** [comment]
用清华大学的镜像，repo太大了没法给

发自我的 iPhone

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
