### ISSUE TITLE
NullPointerException crash from ActionMenuPresenter

### ISSUE THREAD

**Issue by chen-fishbein** [aosp-mirror/platform_frameworks_base#87]
Hi,
I am getting the below stack.
This only occurs on android 6.\* .
The stack does not point from the app code, please advice how to workaround this.

11-11 16:45:12.204: E/AndroidRuntime(6462): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.android.internal.view.menu.MenuBuilder.getVisibleItems()' on a null object reference
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:613)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1082)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.view.menu.MenuBuilder.getNonActionItems(MenuBuilder.java:1114)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.view.menu.MenuPopupHelper$MenuAdapter.getCount(MenuPopupHelper.java:373)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:821)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6179)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.view.menu.MenuPopupHelper$MenuAdapter.notifyDataSetChanged(MenuPopupHelper.java:427)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.view.menu.MenuPopupHelper.updateMenuView(MenuPopupHelper.java:288)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:257)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:976)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:999)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.policy.PhoneWindow.preparePanel(PhoneWindow.java:601)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.policy.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:939)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.policy.PhoneWindow$1.run(PhoneWindow.java:271)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.view.Choreographer.doFrame(Choreographer.java:603)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.os.Handler.handleCallback(Handler.java:739)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.os.Handler.dispatchMessage(Handler.java:95)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.os.Looper.loop(Looper.java:148)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at android.app.ActivityThread.main(ActivityThread.java:5417)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at java.lang.reflect.Method.invoke(Native Method)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-11 16:45:12.204: E/AndroidRuntime(6462):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mwarnett** [comment]
Me Too!

**Comment by chen-fishbein** [comment]
any update on this?

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
